// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: error.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrCode 框架保留错误码
type ErrCode int32

const (
	// 成功
	ErrCode_ERR_CODE_OK ErrCode = 0
	// ---------------------------------------------------------------------
	// 通用错误：1000-1999
	// ---------------------------------------------------------------------
	ErrCode_ERR_CODE_UNKNOWN            ErrCode = 1000 // 未知错误
	ErrCode_ERR_CODE_INVALID_ARGUMENT   ErrCode = 1001 // 无效参数
	ErrCode_ERR_CODE_NOT_FOUND          ErrCode = 1002 // 资源不存在
	ErrCode_ERR_CODE_ALREADY_EXISTS     ErrCode = 1003 // 资源已存在
	ErrCode_ERR_CODE_PERMISSION_DENIED  ErrCode = 1004 // 权限不足
	ErrCode_ERR_CODE_UNAUTHENTICATED    ErrCode = 1005 // 未认证
	ErrCode_ERR_CODE_RESOURCE_EXHAUSTED ErrCode = 1006 // 资源耗尽
	ErrCode_ERR_CODE_INTERNAL           ErrCode = 1007 // 内部错误
	ErrCode_ERR_CODE_UNAVAILABLE        ErrCode = 1008 // 服务不可用
	ErrCode_ERR_CODE_DEADLINE_EXCEEDED  ErrCode = 1009 // 超时
	ErrCode_ERR_CODE_CANCELLED          ErrCode = 1010 // 已取消
	ErrCode_ERR_CODE_DATA_LOSS          ErrCode = 1011 // 数据丢失
	ErrCode_ERR_CODE_ABORTED            ErrCode = 1012 // 操作中止
	// ---------------------------------------------------------------------
	// 数据库错误：2000-2999
	// ---------------------------------------------------------------------
	ErrCode_ERR_CODE_DB_CONNECTION  ErrCode = 2001 // 数据库连接失败
	ErrCode_ERR_CODE_DB_QUERY       ErrCode = 2002 // 查询失败
	ErrCode_ERR_CODE_DB_TRANSACTION ErrCode = 2003 // 事务失败
	ErrCode_ERR_CODE_DB_DUPLICATE   ErrCode = 2004 // 重复记录
	ErrCode_ERR_CODE_DB_CONSTRAINT  ErrCode = 2005 // 约束违反
	ErrCode_ERR_CODE_DB_TIMEOUT     ErrCode = 2006 // 数据库超时
	// ---------------------------------------------------------------------
	// 缓存错误：3000-3999
	// ---------------------------------------------------------------------
	ErrCode_ERR_CODE_CACHE_CONNECTION    ErrCode = 3001 // 缓存连接失败
	ErrCode_ERR_CODE_CACHE_MISS          ErrCode = 3002 // 缓存未命中
	ErrCode_ERR_CODE_CACHE_EXPIRED       ErrCode = 3003 // 缓存已过期
	ErrCode_ERR_CODE_CACHE_SERIALIZATION ErrCode = 3004 // 缓存序列化失败
	// ---------------------------------------------------------------------
	// 外部服务错误：4000-4999
	// ---------------------------------------------------------------------
	ErrCode_ERR_CODE_EXTERNAL_SERVICE     ErrCode = 4001 // 外部服务错误
	ErrCode_ERR_CODE_EXTERNAL_TIMEOUT     ErrCode = 4002 // 外部服务超时
	ErrCode_ERR_CODE_EXTERNAL_UNAVAILABLE ErrCode = 4003 // 外部服务不可用
	// ---------------------------------------------------------------------
	// 认证授权错误：5000-5999
	// ---------------------------------------------------------------------
	ErrCode_ERR_CODE_TOKEN_EXPIRED     ErrCode = 5001 // Token 过期
	ErrCode_ERR_CODE_TOKEN_INVALID     ErrCode = 5002 // Token 无效
	ErrCode_ERR_CODE_TOKEN_MISSING     ErrCode = 5003 // Token 缺失
	ErrCode_ERR_CODE_SESSION_EXPIRED   ErrCode = 5004 // 会话过期
	ErrCode_ERR_CODE_ACCESS_DENIED     ErrCode = 5005 // 访问拒绝
	ErrCode_ERR_CODE_SIGNATURE_INVALID ErrCode = 5006 // 签名无效
	// ---------------------------------------------------------------------
	// 限流熔断错误：6000-6999
	// ---------------------------------------------------------------------
	ErrCode_ERR_CODE_RATE_LIMITED   ErrCode = 6001 // 请求被限流
	ErrCode_ERR_CODE_CIRCUIT_OPEN   ErrCode = 6002 // 熔断器打开
	ErrCode_ERR_CODE_QUOTA_EXCEEDED ErrCode = 6003 // 配额超限
	// ---------------------------------------------------------------------
	// 消息队列错误：7000-7999
	// ---------------------------------------------------------------------
	ErrCode_ERR_CODE_MQ_CONNECTION ErrCode = 7001 // 消息队列连接失败
	ErrCode_ERR_CODE_MQ_PUBLISH    ErrCode = 7002 // 消息发布失败
	ErrCode_ERR_CODE_MQ_CONSUME    ErrCode = 7003 // 消息消费失败
	// ---------------------------------------------------------------------
	// 配置错误：8000-8999
	// ---------------------------------------------------------------------
	ErrCode_ERR_CODE_CONFIG_INVALID     ErrCode = 8001 // 配置无效
	ErrCode_ERR_CODE_CONFIG_MISSING     ErrCode = 8002 // 配置缺失
	ErrCode_ERR_CODE_CONFIG_LOAD_FAILED ErrCode = 8003 // 配置加载失败
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:    "ERR_CODE_OK",
		1000: "ERR_CODE_UNKNOWN",
		1001: "ERR_CODE_INVALID_ARGUMENT",
		1002: "ERR_CODE_NOT_FOUND",
		1003: "ERR_CODE_ALREADY_EXISTS",
		1004: "ERR_CODE_PERMISSION_DENIED",
		1005: "ERR_CODE_UNAUTHENTICATED",
		1006: "ERR_CODE_RESOURCE_EXHAUSTED",
		1007: "ERR_CODE_INTERNAL",
		1008: "ERR_CODE_UNAVAILABLE",
		1009: "ERR_CODE_DEADLINE_EXCEEDED",
		1010: "ERR_CODE_CANCELLED",
		1011: "ERR_CODE_DATA_LOSS",
		1012: "ERR_CODE_ABORTED",
		2001: "ERR_CODE_DB_CONNECTION",
		2002: "ERR_CODE_DB_QUERY",
		2003: "ERR_CODE_DB_TRANSACTION",
		2004: "ERR_CODE_DB_DUPLICATE",
		2005: "ERR_CODE_DB_CONSTRAINT",
		2006: "ERR_CODE_DB_TIMEOUT",
		3001: "ERR_CODE_CACHE_CONNECTION",
		3002: "ERR_CODE_CACHE_MISS",
		3003: "ERR_CODE_CACHE_EXPIRED",
		3004: "ERR_CODE_CACHE_SERIALIZATION",
		4001: "ERR_CODE_EXTERNAL_SERVICE",
		4002: "ERR_CODE_EXTERNAL_TIMEOUT",
		4003: "ERR_CODE_EXTERNAL_UNAVAILABLE",
		5001: "ERR_CODE_TOKEN_EXPIRED",
		5002: "ERR_CODE_TOKEN_INVALID",
		5003: "ERR_CODE_TOKEN_MISSING",
		5004: "ERR_CODE_SESSION_EXPIRED",
		5005: "ERR_CODE_ACCESS_DENIED",
		5006: "ERR_CODE_SIGNATURE_INVALID",
		6001: "ERR_CODE_RATE_LIMITED",
		6002: "ERR_CODE_CIRCUIT_OPEN",
		6003: "ERR_CODE_QUOTA_EXCEEDED",
		7001: "ERR_CODE_MQ_CONNECTION",
		7002: "ERR_CODE_MQ_PUBLISH",
		7003: "ERR_CODE_MQ_CONSUME",
		8001: "ERR_CODE_CONFIG_INVALID",
		8002: "ERR_CODE_CONFIG_MISSING",
		8003: "ERR_CODE_CONFIG_LOAD_FAILED",
	}
	ErrCode_value = map[string]int32{
		"ERR_CODE_OK":                   0,
		"ERR_CODE_UNKNOWN":              1000,
		"ERR_CODE_INVALID_ARGUMENT":     1001,
		"ERR_CODE_NOT_FOUND":            1002,
		"ERR_CODE_ALREADY_EXISTS":       1003,
		"ERR_CODE_PERMISSION_DENIED":    1004,
		"ERR_CODE_UNAUTHENTICATED":      1005,
		"ERR_CODE_RESOURCE_EXHAUSTED":   1006,
		"ERR_CODE_INTERNAL":             1007,
		"ERR_CODE_UNAVAILABLE":          1008,
		"ERR_CODE_DEADLINE_EXCEEDED":    1009,
		"ERR_CODE_CANCELLED":            1010,
		"ERR_CODE_DATA_LOSS":            1011,
		"ERR_CODE_ABORTED":              1012,
		"ERR_CODE_DB_CONNECTION":        2001,
		"ERR_CODE_DB_QUERY":             2002,
		"ERR_CODE_DB_TRANSACTION":       2003,
		"ERR_CODE_DB_DUPLICATE":         2004,
		"ERR_CODE_DB_CONSTRAINT":        2005,
		"ERR_CODE_DB_TIMEOUT":           2006,
		"ERR_CODE_CACHE_CONNECTION":     3001,
		"ERR_CODE_CACHE_MISS":           3002,
		"ERR_CODE_CACHE_EXPIRED":        3003,
		"ERR_CODE_CACHE_SERIALIZATION":  3004,
		"ERR_CODE_EXTERNAL_SERVICE":     4001,
		"ERR_CODE_EXTERNAL_TIMEOUT":     4002,
		"ERR_CODE_EXTERNAL_UNAVAILABLE": 4003,
		"ERR_CODE_TOKEN_EXPIRED":        5001,
		"ERR_CODE_TOKEN_INVALID":        5002,
		"ERR_CODE_TOKEN_MISSING":        5003,
		"ERR_CODE_SESSION_EXPIRED":      5004,
		"ERR_CODE_ACCESS_DENIED":        5005,
		"ERR_CODE_SIGNATURE_INVALID":    5006,
		"ERR_CODE_RATE_LIMITED":         6001,
		"ERR_CODE_CIRCUIT_OPEN":         6002,
		"ERR_CODE_QUOTA_EXCEEDED":       6003,
		"ERR_CODE_MQ_CONNECTION":        7001,
		"ERR_CODE_MQ_PUBLISH":           7002,
		"ERR_CODE_MQ_CONSUME":           7003,
		"ERR_CODE_CONFIG_INVALID":       8001,
		"ERR_CODE_CONFIG_MISSING":       8002,
		"ERR_CODE_CONFIG_LOAD_FAILED":   8003,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_error_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_error_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

// ErrorInfo 业务错误详情
// 用于 gRPC status.Status 的 details 字段
//
// 错误码规范：
//   - 框架保留：0-10000
//   - 业务侧自定义：10001+ (由业务开发者自行规划使用)
type ErrorInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 错误码（整型，支持业务扩展）
	ErrCode int32 `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	// 错误域（模块标识）
	// 如："user", "order", "payment", "auth"
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	// 错误原因（机器可读的错误标识）
	// 如："USER_NOT_FOUND", "INVALID_PASSWORD", "ORDER_EXPIRED"
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// 错误消息（人类可读的描述）
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// 元数据（附加信息）
	// 如：{"user_id": "123", "field": "email"}
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorInfo) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *ErrorInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ErrorInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// FieldViolation 字段校验错误
type FieldViolation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 字段路径
	// 如："user.email", "items[0].quantity"
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// 错误描述
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldViolation) Reset() {
	*x = FieldViolation{}
	mi := &file_error_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldViolation) ProtoMessage() {}

func (x *FieldViolation) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldViolation.ProtoReflect.Descriptor instead.
func (*FieldViolation) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{1}
}

func (x *FieldViolation) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldViolation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ValidationError 参数校验错误详情
// 用于批量返回多个字段的校验错误
type ValidationError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 校验失败的字段列表
	Violations    []*FieldViolation `protobuf:"bytes,1,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_error_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationError) GetViolations() []*FieldViolation {
	if x != nil {
		return x.Violations
	}
	return nil
}

// RetryInfo 重试信息
// 告知客户端何时可以重试
type RetryInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 建议重试延迟（秒）
	RetryDelaySeconds int32 `protobuf:"varint,1,opt,name=retry_delay_seconds,json=retryDelaySeconds,proto3" json:"retry_delay_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RetryInfo) Reset() {
	*x = RetryInfo{}
	mi := &file_error_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryInfo) ProtoMessage() {}

func (x *RetryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryInfo.ProtoReflect.Descriptor instead.
func (*RetryInfo) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{3}
}

func (x *RetryInfo) GetRetryDelaySeconds() int32 {
	if x != nil {
		return x.RetryDelaySeconds
	}
	return 0
}

// DebugInfo 调试信息
// 仅在开发/测试环境返回，生产环境应过滤
type DebugInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 错误堆栈
	StackEntries []string `protobuf:"bytes,1,rep,name=stack_entries,json=stackEntries,proto3" json:"stack_entries,omitempty"`
	// 详细描述
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugInfo) Reset() {
	*x = DebugInfo{}
	mi := &file_error_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugInfo) ProtoMessage() {}

func (x *DebugInfo) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugInfo.ProtoReflect.Descriptor instead.
func (*DebugInfo) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{4}
}

func (x *DebugInfo) GetStackEntries() []string {
	if x != nil {
		return x.StackEntries
	}
	return nil
}

func (x *DebugInfo) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_error_proto protoreflect.FileDescriptor

const file_error_proto_rawDesc = "" +
	"\n" +
	"\verror.proto\x12\x06common\"\xea\x01\n" +
	"\tErrorInfo\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12;\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1f.common.ErrorInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x0eFieldViolation\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"I\n" +
	"\x0fValidationError\x126\n" +
	"\n" +
	"violations\x18\x01 \x03(\v2\x16.common.FieldViolationR\n" +
	"violations\";\n" +
	"\tRetryInfo\x12.\n" +
	"\x13retry_delay_seconds\x18\x01 \x01(\x05R\x11retryDelaySeconds\"H\n" +
	"\tDebugInfo\x12#\n" +
	"\rstack_entries\x18\x01 \x03(\tR\fstackEntries\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail*\xc4\t\n" +
	"\aErrCode\x12\x0f\n" +
	"\vERR_CODE_OK\x10\x00\x12\x15\n" +
	"\x10ERR_CODE_UNKNOWN\x10\xe8\a\x12\x1e\n" +
	"\x19ERR_CODE_INVALID_ARGUMENT\x10\xe9\a\x12\x17\n" +
	"\x12ERR_CODE_NOT_FOUND\x10\xea\a\x12\x1c\n" +
	"\x17ERR_CODE_ALREADY_EXISTS\x10\xeb\a\x12\x1f\n" +
	"\x1aERR_CODE_PERMISSION_DENIED\x10\xec\a\x12\x1d\n" +
	"\x18ERR_CODE_UNAUTHENTICATED\x10\xed\a\x12 \n" +
	"\x1bERR_CODE_RESOURCE_EXHAUSTED\x10\xee\a\x12\x16\n" +
	"\x11ERR_CODE_INTERNAL\x10\xef\a\x12\x19\n" +
	"\x14ERR_CODE_UNAVAILABLE\x10\xf0\a\x12\x1f\n" +
	"\x1aERR_CODE_DEADLINE_EXCEEDED\x10\xf1\a\x12\x17\n" +
	"\x12ERR_CODE_CANCELLED\x10\xf2\a\x12\x17\n" +
	"\x12ERR_CODE_DATA_LOSS\x10\xf3\a\x12\x15\n" +
	"\x10ERR_CODE_ABORTED\x10\xf4\a\x12\x1b\n" +
	"\x16ERR_CODE_DB_CONNECTION\x10\xd1\x0f\x12\x16\n" +
	"\x11ERR_CODE_DB_QUERY\x10\xd2\x0f\x12\x1c\n" +
	"\x17ERR_CODE_DB_TRANSACTION\x10\xd3\x0f\x12\x1a\n" +
	"\x15ERR_CODE_DB_DUPLICATE\x10\xd4\x0f\x12\x1b\n" +
	"\x16ERR_CODE_DB_CONSTRAINT\x10\xd5\x0f\x12\x18\n" +
	"\x13ERR_CODE_DB_TIMEOUT\x10\xd6\x0f\x12\x1e\n" +
	"\x19ERR_CODE_CACHE_CONNECTION\x10\xb9\x17\x12\x18\n" +
	"\x13ERR_CODE_CACHE_MISS\x10\xba\x17\x12\x1b\n" +
	"\x16ERR_CODE_CACHE_EXPIRED\x10\xbb\x17\x12!\n" +
	"\x1cERR_CODE_CACHE_SERIALIZATION\x10\xbc\x17\x12\x1e\n" +
	"\x19ERR_CODE_EXTERNAL_SERVICE\x10\xa1\x1f\x12\x1e\n" +
	"\x19ERR_CODE_EXTERNAL_TIMEOUT\x10\xa2\x1f\x12\"\n" +
	"\x1dERR_CODE_EXTERNAL_UNAVAILABLE\x10\xa3\x1f\x12\x1b\n" +
	"\x16ERR_CODE_TOKEN_EXPIRED\x10\x89'\x12\x1b\n" +
	"\x16ERR_CODE_TOKEN_INVALID\x10\x8a'\x12\x1b\n" +
	"\x16ERR_CODE_TOKEN_MISSING\x10\x8b'\x12\x1d\n" +
	"\x18ERR_CODE_SESSION_EXPIRED\x10\x8c'\x12\x1b\n" +
	"\x16ERR_CODE_ACCESS_DENIED\x10\x8d'\x12\x1f\n" +
	"\x1aERR_CODE_SIGNATURE_INVALID\x10\x8e'\x12\x1a\n" +
	"\x15ERR_CODE_RATE_LIMITED\x10\xf1.\x12\x1a\n" +
	"\x15ERR_CODE_CIRCUIT_OPEN\x10\xf2.\x12\x1c\n" +
	"\x17ERR_CODE_QUOTA_EXCEEDED\x10\xf3.\x12\x1b\n" +
	"\x16ERR_CODE_MQ_CONNECTION\x10\xd96\x12\x18\n" +
	"\x13ERR_CODE_MQ_PUBLISH\x10\xda6\x12\x18\n" +
	"\x13ERR_CODE_MQ_CONSUME\x10\xdb6\x12\x1c\n" +
	"\x17ERR_CODE_CONFIG_INVALID\x10\xc1>\x12\x1c\n" +
	"\x17ERR_CODE_CONFIG_MISSING\x10\xc2>\x12 \n" +
	"\x1bERR_CODE_CONFIG_LOAD_FAILED\x10\xc3>B0Z.github.com/xDooria/xDooria-proto-common;commonb\x06proto3"

var (
	file_error_proto_rawDescOnce sync.Once
	file_error_proto_rawDescData []byte
)

func file_error_proto_rawDescGZIP() []byte {
	file_error_proto_rawDescOnce.Do(func() {
		file_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)))
	})
	return file_error_proto_rawDescData
}

var file_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_error_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_error_proto_goTypes = []any{
	(ErrCode)(0),            // 0: common.ErrCode
	(*ErrorInfo)(nil),       // 1: common.ErrorInfo
	(*FieldViolation)(nil),  // 2: common.FieldViolation
	(*ValidationError)(nil), // 3: common.ValidationError
	(*RetryInfo)(nil),       // 4: common.RetryInfo
	(*DebugInfo)(nil),       // 5: common.DebugInfo
	nil,                     // 6: common.ErrorInfo.MetadataEntry
}
var file_error_proto_depIdxs = []int32{
	6, // 0: common.ErrorInfo.metadata:type_name -> common.ErrorInfo.MetadataEntry
	2, // 1: common.ValidationError.violations:type_name -> common.FieldViolation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_error_proto_init() }
func file_error_proto_init() {
	if File_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_proto_goTypes,
		DependencyIndexes: file_error_proto_depIdxs,
		EnumInfos:         file_error_proto_enumTypes,
		MessageInfos:      file_error_proto_msgTypes,
	}.Build()
	File_error_proto = out.File
	file_error_proto_goTypes = nil
	file_error_proto_depIdxs = nil
}
