// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: opcode.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpCode 系统级协议号 (0 - 999)
type OpCode int32

const (
	OpCode_OP_NONE OpCode = 0
	// 基础连接协议
	OpCode_OP_HEARTBEAT    OpCode = 1 // 心跳包
	OpCode_OP_ERROR_NOTICE OpCode = 2 // 通用错误通知
	OpCode_OP_KICK_NOTICE  OpCode = 3 // 踢人通知
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0: "OP_NONE",
		1: "OP_HEARTBEAT",
		2: "OP_ERROR_NOTICE",
		3: "OP_KICK_NOTICE",
	}
	OpCode_value = map[string]int32{
		"OP_NONE":         0,
		"OP_HEARTBEAT":    1,
		"OP_ERROR_NOTICE": 2,
		"OP_KICK_NOTICE":  3,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_opcode_proto_enumTypes[0].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_opcode_proto_enumTypes[0]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_opcode_proto_rawDescGZIP(), []int{0}
}

var File_opcode_proto protoreflect.FileDescriptor

const file_opcode_proto_rawDesc = "" +
	"\n" +
	"\fopcode.proto\x12\x06common*P\n" +
	"\x06OpCode\x12\v\n" +
	"\aOP_NONE\x10\x00\x12\x10\n" +
	"\fOP_HEARTBEAT\x10\x01\x12\x13\n" +
	"\x0fOP_ERROR_NOTICE\x10\x02\x12\x12\n" +
	"\x0eOP_KICK_NOTICE\x10\x03B5Z3github.com/lk2023060901/xdooria-proto-common;commonb\x06proto3"

var (
	file_opcode_proto_rawDescOnce sync.Once
	file_opcode_proto_rawDescData []byte
)

func file_opcode_proto_rawDescGZIP() []byte {
	file_opcode_proto_rawDescOnce.Do(func() {
		file_opcode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_opcode_proto_rawDesc), len(file_opcode_proto_rawDesc)))
	})
	return file_opcode_proto_rawDescData
}

var file_opcode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_opcode_proto_goTypes = []any{
	(OpCode)(0), // 0: common.OpCode
}
var file_opcode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_opcode_proto_init() }
func file_opcode_proto_init() {
	if File_opcode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_opcode_proto_rawDesc), len(file_opcode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_opcode_proto_goTypes,
		DependencyIndexes: file_opcode_proto_depIdxs,
		EnumInfos:         file_opcode_proto_enumTypes,
	}.Build()
	File_opcode_proto = out.File
	file_opcode_proto_goTypes = nil
	file_opcode_proto_depIdxs = nil
}
